// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"git.code.tencent.com/houseme/ask-go-api/app/dao/internal"
)

// tagMapDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type tagMapDao struct {
	*internal.TagMapDao
}

var (
	// TagMap is globally public accessible object for table {TplTableName} operations.
	TagMap = &tagMapDao{
		internal.TagMap,
	}
)

// Fill with you ideas below.
