// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Article is the golang structure for table article.
type Article struct {
	Id          uint64      `orm:"id,primary"       json:"id"`          // 文章ID
	Cid         uint        `orm:"cid"              json:"cid"`         // 栏目id
	Scid        string      `orm:"scid"             json:"scid"`        // 副栏目
	Pid         string      `orm:"pid"              json:"pid"`         // 属性
	SortNum     uint        `orm:"sort_num"         json:"sort_num"`    // 排序
	Title       string      `orm:"title"            json:"title"`       // 标题
	SubTitle    string      `orm:"sub_title"        json:"sub_title"`   // 短标题
	Clink       string      `orm:"clink"            json:"clink"`       // 自定义链接
	Url         string      `orm:"url"              json:"url"`         // 外部链接
	Keywords    string      `orm:"keywords"         json:"keywords"`    // 关键词
	Tags        string      `orm:"tags"             json:"tags"`        // 标签
	Description string      `orm:"description"      json:"description"` // 摘要
	PublicTime  *gtime.Time `orm:"public_time"      json:"public_time"` // 发布时间
	PostTime    *gtime.Time `orm:"post_time"        json:"post_time"`   // 提交时间
	Hits        uint64      `orm:"hits"             json:"hits"`        // 总点击数
	HitsToday   uint        `orm:"hits_today"       json:"hits_today"`  // 当天点击数
	HitsYday    uint        `orm:"hits_yday"        json:"hits_yday"`   // 昨天点击数
	HitsWeek    uint        `orm:"hits_week"        json:"hits_week"`   // 周点击
	HitsMonth   uint        `orm:"hits_month"       json:"hits_month"`  // 月点击
	Favorite    uint        `orm:"favorite"         json:"favorite"`    // 收藏数
	Comments    uint        `orm:"comments"         json:"comments"`    // 评论数
	Good        uint        `orm:"good"             json:"good"`        // 顶
	Bad         uint        `orm:"bad"              json:"bad"`         // 踩
	Creative    uint        `orm:"creative"         json:"creative"`    // 文章类型 1原创 0转载
	Weight      int         `orm:"weight"           json:"weight"`      // 权重
	Md5Value    string      `orm:"md5_value,unique" json:"md_5_value"`  // MD5加密值
	SourceUrl   string      `orm:"source_url"       json:"source_url"`  // 原始URL
	State       uint        `orm:"state"            json:"state"`       // [[0:草稿],[1:正常],[2:回收],[3:审核],[4:不合格]]
	CreateTime  *gtime.Time `orm:"create_time"      json:"create_time"` // 创建时间
	ModifyTime  *gtime.Time `orm:"modify_time"      json:"modify_time"` // 更新时间
}
