// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Lunar is the golang structure for table lunar.
type Lunar struct {
	Id         uint64      `orm:"id,primary"  json:"id"`          // ID
	Yeartime   uint        `orm:"yeartime"    json:"yeartime"`    // 年份
	Monthtime  uint        `orm:"monthtime"   json:"monthtime"`   // 月份
	Daytime    int         `orm:"daytime"     json:"daytime"`     // 日期
	BgImg      string      `orm:"bg_img"      json:"bg_img"`      // 背景图
	Weather    string      `orm:"weather"     json:"weather"`     // 天气内容
	Content    string      `orm:"content"     json:"content"`     // 万年历内容
	CreateTime *gtime.Time `orm:"create_time" json:"create_time"` // 创建时间
	ModifyTime *gtime.Time `orm:"modify_time" json:"modify_time"` // 修改时间
}
