// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Tag is the golang structure for table tag.
type Tag struct {
	Id          uint64      `orm:"id,primary"  json:"id"`          //
	Cid         uint        `orm:"cid"         json:"cid"`         //
	Tkey        string      `orm:"tkey"        json:"tkey"`        //
	Title       string      `orm:"title"       json:"title"`       // 标题
	Name        string      `orm:"name"        json:"name"`        //
	SeoTitle    string      `orm:"seo_title"   json:"seo_title"`   //
	SubTitle    string      `orm:"sub_title"   json:"sub_title"`   //
	Keywords    string      `orm:"keywords"    json:"keywords"`    //
	Description string      `orm:"description" json:"description"` //
	Url         string      `orm:"url"         json:"url"`         //
	Weight      int         `orm:"weight"      json:"weight"`      //
	Clink       string      `orm:"clink"       json:"clink"`       //
	Sortnum     uint        `orm:"sortnum"     json:"sortnum"`     //
	PublicTime  *gtime.Time `orm:"public_time" json:"public_time"` // 发布时间
	PostTime    *gtime.Time `orm:"post_time"   json:"post_time"`   // 提交时间
	Hits        uint64      `orm:"hits"        json:"hits"`        // 总点击数
	HitsToday   uint        `orm:"hits_today"  json:"hits_today"`  // 当天点击数
	HitsYday    uint        `orm:"hits_yday"   json:"hits_yday"`   // 昨天点击数
	HitsWeek    uint        `orm:"hits_week"   json:"hits_week"`   // 周点击
	HitsMonth   uint        `orm:"hits_month"  json:"hits_month"`  // 月点击
	Count       uint        `orm:"count"       json:"count"`       //
	Comments    uint        `orm:"comments"    json:"comments"`    //
	Favorite    uint        `orm:"favorite"    json:"favorite"`    // 收藏数
	Good        uint        `orm:"good"        json:"good"`        // 顶
	Bad         uint        `orm:"bad"         json:"bad"`         // 踩
	State       uint        `orm:"state"       json:"state"`       //
	CreateTime  *gtime.Time `orm:"create_time" json:"create_time"` // 创建时间
	ModifyTime  *gtime.Time `orm:"modify_time" json:"modify_time"` // 更新时间
}
