// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserCollection is the golang structure for table user_collection.
type UserCollection struct {
	Id         uint64      `orm:"id,primary"  json:"id"`          // 主键id
	UserNo     uint64      `orm:"user_no"     json:"user_no"`     // 用户id
	ArticleId  uint64      `orm:"article_id"  json:"article_id"`  // 主题id
	CategoryId uint        `orm:"category_id" json:"category_id"` // 分类id
	State      uint        `orm:"state"       json:"state"`       // 收藏状态200:正常 ;100:取消
	CreateTime *gtime.Time `orm:"create_time" json:"create_time"` // 创建时间
	ModifyTime *gtime.Time `orm:"modify_time" json:"modify_time"` // 更新时间
}
