// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserAuth is the golang structure for table user_auth.
type UserAuth struct {
	Id           uint64      `orm:"id,primary"    json:"id"`            //
	UserNo       uint64      `orm:"user_no"       json:"user_no"`       // 关联用户ID
	AuthAccount  string      `orm:"auth_account"  json:"auth_account"`  // 登录ID
	AuthPassword string      `orm:"auth_password" json:"auth_password"` // 登录密码
	AuthType     string      `orm:"auth_type"     json:"auth_type"`     // 账号类型 wechat、welite、app
	LoginIp      string      `orm:"login_ip"      json:"login_ip"`      // 最近登录IP
	LoginTime    *gtime.Time `orm:"login_time"    json:"login_time"`    // 最近登录时间
	AuthState    uint        `orm:"auth_state"    json:"auth_state"`    // 状态 默认100，100正常，90禁用
	CreateTime   *gtime.Time `orm:"create_time"   json:"create_time"`   // 创建时间
	ModifyTime   *gtime.Time `orm:"modify_time"   json:"modify_time"`   // 更新时间
}
