// ==========================================================================
// This is auto-generated by gf cli tool. You may not really want to edit it.
// ==========================================================================

package internal

import (
	"database/sql"
	"time"

	"git.code.tencent.com/houseme/ask-go-api/app/model"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserCollectionDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserCollectionDao struct {
	gmvc.M
	Table   string
	Columns userCollectionColumns
}

// UserCollectionColumns defines and stores column names for table user_collection.
type userCollectionColumns struct {
	Id         string // 主键id
	UserNo     string // 用户id
	ArticleId  string // 主题id
	CategoryId string // 分类id
	State      string // 收藏状态200:正常 ;100:取消
	CreateTime string // 创建时间
	ModifyTime string // 更新时间
}

var (
	// UserCollection is globally public accessible object for table user_collection operations.
	UserCollection = &UserCollectionDao{
		M:     g.DB("default").Table("user_collection").Safe(),
		Table: "user_collection",
		Columns: userCollectionColumns{
			Id:         "id",
			UserNo:     "user_no",
			ArticleId:  "article_id",
			CategoryId: "category_id",
			State:      "state",
			CreateTime: "create_time",
			ModifyTime: "modify_time",
		},
	}
)

// As sets an alias name for current table.
func (d *UserCollectionDao) As(as string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.As(as)}
}

// TX sets the transaction for current operation.
func (d *UserCollectionDao) TX(tx *gdb.TX) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.TX(tx)}
}

// Master marks the following operation on master node.
func (d *UserCollectionDao) Master() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Master()}
}

// Slave marks the following operation on slave node.
// Note that it makes sense only if there's any slave node configured.
func (d *UserCollectionDao) Slave() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Slave()}
}

// Args sets custom arguments for model operation.
func (d *UserCollectionDao) Args(args ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Args(args...)}
}

// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *UserCollectionDao) LeftJoin(table ...string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.LeftJoin(table...)}
}

// RightJoin does "RIGHT JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").RightJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").RightJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *UserCollectionDao) RightJoin(table ...string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.RightJoin(table...)}
}

// InnerJoin does "INNER JOIN ... ON ..." statement on the model.
// The parameter <table> can be joined table and its joined condition,
// and also with its alias name, like:
// Table("user").InnerJoin("user_detail", "user_detail.uid=user.uid")
// Table("user", "u").InnerJoin("user_detail", "ud", "ud.uid=u.uid")
func (d *UserCollectionDao) InnerJoin(table ...string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.InnerJoin(table...)}
}

// Fields sets the operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *UserCollectionDao) Fields(fieldNamesOrMapStruct ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Fields(fieldNamesOrMapStruct...)}
}

// FieldsEx sets the excluded operation fields of the model, multiple fields joined using char ','.
// The parameter <fieldNamesOrMapStruct> can be type of string/map/*map/struct/*struct.
func (d *UserCollectionDao) FieldsEx(fieldNamesOrMapStruct ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.FieldsEx(fieldNamesOrMapStruct...)}
}

// Option sets the extra operation option for the model.
func (d *UserCollectionDao) Option(option int) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Option(option)}
}

// OmitEmpty sets OPTION_OMITEMPTY option for the model, which automatically filers
// the data and where attributes for empty values.
func (d *UserCollectionDao) OmitEmpty() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.OmitEmpty()}
}

// Filter marks filtering the fields which does not exist in the fields of the operated table.
func (d *UserCollectionDao) Filter() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Filter()}
}

// Where sets the condition statement for the model. The parameter <where> can be type of
// string/map/gmap/slice/struct/*struct, etc. Note that, if it's called more than one times,
// multiple conditions will be joined into where statement using "AND".
// Eg:
// Where("uid=10000")
// Where("uid", 10000)
// Where("money>? AND name like ?", 99999, "vip_%")
// Where("uid", 1).Where("name", "john")
// Where("status IN (?)", g.Slice{1,2,3})
// Where("age IN(?,?)", 18, 50)
// Where(User{ Id : 1, UserName : "john"})
func (d *UserCollectionDao) Where(where interface{}, args ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Where(where, args...)}
}

// WherePri does the same logic as M.Where except that if the parameter <where>
// is a single condition like int/string/float/slice, it treats the condition as the primary
// key value. That is, if primary key is "id" and given <where> parameter as "123", the
// WherePri function treats the condition as "id=123", but M.Where treats the condition
// as string "123".
func (d *UserCollectionDao) WherePri(where interface{}, args ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.WherePri(where, args...)}
}

// And adds "AND" condition to the where statement.
func (d *UserCollectionDao) And(where interface{}, args ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.And(where, args...)}
}

// Or adds "OR" condition to the where statement.
func (d *UserCollectionDao) Or(where interface{}, args ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Or(where, args...)}
}

// Group sets the "GROUP BY" statement for the model.
func (d *UserCollectionDao) Group(groupBy string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Group(groupBy)}
}

// Order sets the "ORDER BY" statement for the model.
func (d *UserCollectionDao) Order(orderBy ...string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Order(orderBy...)}
}

// Limit sets the "LIMIT" statement for the model.
// The parameter <limit> can be either one or two number, if passed two number is passed,
// it then sets "LIMIT limit[0],limit[1]" statement for the model, or else it sets "LIMIT limit[0]"
// statement.
func (d *UserCollectionDao) Limit(limit ...int) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Limit(limit...)}
}

// Offset sets the "OFFSET" statement for the model.
// It only makes sense for some databases like SQLServer, PostgreSQL, etc.
func (d *UserCollectionDao) Offset(offset int) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Offset(offset)}
}

// Page sets the paging number for the model.
// The parameter <page> is started from 1 for paging.
// Note that, it differs that the Limit function start from 0 for "LIMIT" statement.
func (d *UserCollectionDao) Page(page, limit int) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Page(page, limit)}
}

// Batch sets the batch operation number for the model.
func (d *UserCollectionDao) Batch(batch int) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Batch(batch)}
}

// Cache sets the cache feature for the model. It caches the result of the sql, which means
// if there's another same sql request, it just reads and returns the result from cache, it
// but not committed and executed into the database.
//
// If the parameter <duration> < 0, which means it clear the cache with given <name>.
// If the parameter <duration> = 0, which means it never expires.
// If the parameter <duration> > 0, which means it expires after <duration>.
//
// The optional parameter <name> is used to bind a name to the cache, which means you can later
// control the cache like changing the <duration> or clearing the cache with specified <name>.
//
// Note that, the cache feature is disabled if the model is operating on a transaction.
func (d *UserCollectionDao) Cache(duration time.Duration, name ...string) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Cache(duration, name...)}
}

// Data sets the operation data for the model.
// The parameter <data> can be type of string/map/gmap/slice/struct/*struct, etc.
// Eg:
// Data("uid=10000")
// Data("uid", 10000)
// Data(g.Map{"uid": 10000, "name":"john"})
// Data(g.Slice{g.Map{"uid": 10000, "name":"john"}, g.Map{"uid": 20000, "name":"smith"})
func (d *UserCollectionDao) Data(data ...interface{}) *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Data(data...)}
}

// All does "SELECT FROM ..." statement for the model.
// It retrieves the records from table and returns the result as []*model.UserCollection.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *UserCollectionDao) All(where ...interface{}) ([]*model.UserCollection, error) {
	all, err := d.M.All(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.UserCollection
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// One retrieves one record from table and returns the result as *model.UserCollection.
// It returns nil if there's no record retrieved with the given conditions from table.
//
// The optional parameter <where> is the same as the parameter of M.Where function,
// see M.Where.
func (d *UserCollectionDao) One(where ...interface{}) (*model.UserCollection, error) {
	one, err := d.M.One(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.UserCollection
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindOne retrieves and returns a single Record by M.WherePri and M.One.
// Also see M.WherePri and M.One.
func (d *UserCollectionDao) FindOne(where ...interface{}) (*model.UserCollection, error) {
	one, err := d.M.FindOne(where...)
	if err != nil {
		return nil, err
	}
	var entity *model.UserCollection
	if err = one.Struct(&entity); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entity, nil
}

// FindAll retrieves and returns Result by by M.WherePri and M.All.
// Also see M.WherePri and M.All.
func (d *UserCollectionDao) FindAll(where ...interface{}) ([]*model.UserCollection, error) {
	all, err := d.M.FindAll(where...)
	if err != nil {
		return nil, err
	}
	var entities []*model.UserCollection
	if err = all.Structs(&entities); err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	return entities, nil
}

// Chunk iterates the table with given size and callback function.
func (d *UserCollectionDao) Chunk(limit int, callback func(entities []*model.UserCollection, err error) bool) {
	d.M.Chunk(limit, func(result gdb.Result, err error) bool {
		var entities []*model.UserCollection
		err = result.Structs(&entities)
		if err == sql.ErrNoRows {
			return false
		}
		return callback(entities, err)
	})
}

// LockUpdate sets the lock for update for current operation.
func (d *UserCollectionDao) LockUpdate() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.LockUpdate()}
}

// LockShared sets the lock in share mode for current operation.
func (d *UserCollectionDao) LockShared() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.LockShared()}
}

// Unscoped enables/disables the soft deleting feature.
func (d *UserCollectionDao) Unscoped() *UserCollectionDao {
	return &UserCollectionDao{M: d.M.Unscoped()}
}
