// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// ArticleData is the golang structure for table article_data.
type ArticleData internal.ArticleData

// Fill with you ideas below.
