// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// Article is the golang structure for table article.
type Article internal.Article

// Fill with you ideas below.
