// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// Lunar is the golang structure for table lunar.
type Lunar internal.Lunar

// Fill with you ideas below.
