// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// Tag is the golang structure for table tag.
type Tag internal.Tag

// Fill with you ideas below.
