// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// TagMap is the golang structure for table tag_map.
type TagMap internal.TagMap

// Fill with you ideas below.
