// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// ThemeMap is the golang structure for table theme_map.
type ThemeMap internal.ThemeMap

// Fill with you ideas below.
