// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// Theme is the golang structure for table theme.
type Theme internal.Theme

// Fill with you ideas below.
