// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// Fill with you ideas below.
