// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// UserCollection is the golang structure for table user_collection.
type UserCollection internal.UserCollection

// Fill with you ideas below.
