// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"git.code.tencent.com/houseme/ask-go-api/app/model/internal"
)

// UserAuth is the golang structure for table user_auth.
type UserAuth internal.UserAuth

// Fill with you ideas below.
